// Login
export const IS_LOADING = "IS_LOADING";
export const ADD_LOGIN_ERROR = "ADD_LOGIN_ERROR";
export const ADD_LOGIN_LOADING = "ADD_LOGIN_LOADING";
export const ADD_LOGIN_SUCCESS = "ADD_LOGIN_SUCCESS";
export const GET_PROFILE_USER = "GET_PROFILE_USER";
export const LOGOUT = "LOGOUT";
export const UPDATE_PROFILE_USER = "UPDATE_PROFILE_USER";
export const SIGNUP_DATA = "SIGNUP_DATA";
export const GET_ALL_USERS_DATA = "GET_ALL_USERS_DATA";
export const DELETE_PROFILE_USER = "DELETE_PROFILE_USER";
export const GET_ALL_DEACTIVE_USERS_DATA = "GET_ALL_DEACTIVE_USERS_DATA";
export const RECOVER_PROFILE_USER = "RECOVER_PROFILE_USER";
export const RESET_GLOBAL_STATE = "RESET_GLOBAL_STATE";

//AirPort
export const ADD_AIRPORT = "ADD_AIRPORT";
export const UPDATE_AIRPORT = "UPDATE_AIRPORT";
export const DELETE_AIRPORT = "DELETE_AIRPORT";
export const GET_ALL_AIRPORT = " GET_ALL_AIRPORT";
export const AIRPORT_LOADING_TRUE = "AIRPORT_LOADING_TRUE";
export const AIRPORT_LOADING_FALSE = "AIRPORT_LOADING_FALSE";

//CITY
export const GET_ALL_CITY = "GET_ALL_CITY";
export const ADD_CITY = "ADD_CITY";
export const UPDATE_CITY = "UPDATE_CITY";
export const DELETE_CITY = "DELETE_CITY";

//STATE
export const GET_ALL_STATE = "GET_ALL_STATE";
export const ADD_STATE = "ADD_STATE";
export const UPDATE_STATE = "UPDATE_STATE";
export const DELETE_STATE = "DELETE_STATE";

//Local Hourly
export const ADD_LOCAL_HOURLY = "ADD_LOCAL_HOURLY";
export const UPDATE_LOCAL_HOURLY = "UPDATE_LOCAL_HOURLY";
export const DELETE_LOCAL_HOURLY = "DELETE_LOCAL_HOURLY";
export const GET_ALL_LOCAL_HOURLY = "GET_ALL_LOCAL_HOURLY";

//TRIP
export const GET_ALL_TRIP = "GET_ALL_TRIP";
export const UPDATE_TRIP = "UPDATE_TRIP";
export const DELETE_TRIP = "DELETE_TRIP";
export const ADD_TRIP = "ADD_TRIP";


// Destination
export const ADD_DESTINATION = "ADD_DESTINATION";
export const UPDATE_DESTINATION = "UPDATE_DESTINATION";
export const DELETE_DESTINATION = "DELETE_DESTINATION";
export const GET_ALL_DESTINATION = "GET_ALL_DESTINATION";
export const ADD_DESTINATION_LANDMARK = "ADD_DESTINATION_LANDMARK";
export const DESTINATION_LOADING_FALSE ="DESTINATION_LOADING_FALSE";
export const DESTINATION_LOADING_TRUE ="DESTINATION_LOADING_TRUE";
